" vim: set ft=vim:

" Install/update plug----------- {{{
 if empty(glob('~/.vim/autoload/plug.vim'))
   silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
     \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
   autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
 endif

call plug#begin('~/.vim/plugged')
    Plug 'junegunn/vim-plug'
    Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
    Plug 'mhinz/vim-startify'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
call plug#end()
 " }}}

" Pathogen ----------- {{{
" FZF shadows the :Helptags, but it still can be done using
" :call pathogen#helptags()
call pathogen#infect()
call pathogen#helptags()
" }}}

" General Settings----------- {{{
syntax on
filetype plugin indent on

set nocompatible              " required
set hidden
" disabled in favor of ctrl-space
set showtabline=0
" uses a caseinsensitive search unless caps are
" put inside search string
set ignorecase "required for smartcase
set smartcase
set conceallevel=0 "usefful for latex, hides $ signs and such things...

if filereadable(expand("~/.vimrc_background"))
  source ~/.vimrc_background
endif
set encoding=utf-8
set t_Co=256                                " 256 colors
colorscheme wombat256mod
colorscheme gruvbox "wombat256mod
set guifont=mononoki\ Nerd\ Font\ 18
let g:airline_theme='minimalist'                " set airline theme
let g:airline_powerline_fonts = 1

source ~/.vim_mapping

set shell=/bin/bash
set number relativenumber

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

set ruler
set ttyfast                                 " terminal acceleration

set tabstop=4                               " 4 whitespaces for tabs visual presentation
set shiftwidth=4                            " shift lines by 4 spaces
set smarttab                                " set tabs for a shifttabs logic
set expandtab                               " expand tabs into spaces
set autoindent                              " indent when moving to the next line while writing code
" ============ open splits on the bottom or to the right =================
set splitright
set splitbelow

set cursorline                              " shows line under the cursor's line
set showmatch                               " shows matching part of bracket pairs (), [], {}

set nobackup 	                            " no backup files
set nowritebackup                           " only in case you don't want a backup file while editing
set noswapfile 	                            " no swap files

set backspace=indent,eol,start              " backspace removes all (indents, EOLs, start) What is start?

set scrolloff=10                            " let 10 lines before/after cursor during scroll

set clipboard=unnamed                       " use system clipboard

set exrc                                    " enable usage of additional .vimrc files from working directory
set secure                                  " prohibit .vimrc files to execute shell, create files, etc...

" this is from some thoughtbot tutorial and resizes the currently active
" 'window' to be as large as possible
set winwidth=84
set winheight=5
set winminheight=5
set winheight=999
" }}}

" Tabs/BufferSettings" ----------- {{{
" some tab mod...
" tab sball
" some ...tab modifier. not sure what this does
" set switchbuf=useopen
" always have statusbar
set laststatus=2
" }}}

" Search Settings----------- {{{
set incsearch	                            " incremental search
set hlsearch	                            " highlight search results
" }}}

" Tagbar settings----------- {{{
let g:tagbar_autofocus=1
let g:tagbar_width=42

let g:tagbar_type_json = {
    \ 'ctagstype' : 'json',
    \ 'kinds' : [
      \ 'o:objects',
      \ 'a:arrays',
      \ 'n:numbers',
      \ 's:strings',
      \ 'b:booleans',
      \ 'z:nulls'
    \ ],
  \ 'sro' : '.',
    \ 'scope2kind': {
    \ 'object': 'o',
      \ 'ARRAY': 'a',
      \ 'number': 'n',
      \ 'string': 's',
      \ 'boolean': 'b',
      \ 'null': 'z'
    \ },
    \ 'kind2scope': {
    \ 'o': 'object',
      \ 'a': 'array',
      \ 'n': 'number',
      \ 's': 'string',
      \ 'b': 'boolean',
      \ 'z': 'null'
    \ },
    \ 'sort' : 0
    \ }
" }}}

""NERDTree settings ----------- {{{
let NERDTreeIgnore=['\.pyc$', '\.pyo$', '__pycache__$']     " Ignore files in NERDTree
let NERDTreeWinSize=40
" toggle nerdtree on cn...
nnoremap <C-n> :NERDTreeToggle<CR><C-C>
" }}}

" NERDCommenter settings" ----------- {{{
" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1

" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1

" Align line-wise comment delimiters flush left instead of following code indentation
let g:NERDDefaultAlign = 'left'

" Set a language to use its alternate delimiters by default
let g:NERDAltDelims_java = 1

" Add your own custom formats or override the defaults
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }

" Allow commenting and inverting empty lines (useful when commenting a region)
let g:NERDCommentEmptyLines = 1

" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1
" }}}

" Indent guide settings----------- {{{
set listchars=tab:›\ ,trail:•,extends:#,nbsp:.
" }}}

" Maybe remove this plugin. Im not going to use it anyways...
" " Python-mode settings" ----------- {{{
" python executables for different plugins
" pymode settings
let g:pymode = 1
let g:pymode_warnings = 1
" let g:pymode_paths = []
"trim whitespace on save
let g:pymode_trim_whitespaces = 1
let g:pymode_options = 1
let g:pymode_python='python3'
let g:pymode_options_max_line_length = 87
" ====  ============================
" Key   Command
" ====  ============================
" [[    Jump to previous class or function (normal, visual, operator modes)
" ]]    Jump to next class or function  (normal, visual, operator modes)
" [M    Jump to previous class or method (normal, visual, operator modes)
" ]M    Jump to next class or method (normal, visual, operator modes)
" aC    Select a class. Ex: vaC, daC, yaC, caC (normal, operator modes)
" iC    Select inner class. Ex: viC, diC, yiC, ciC (normal, operator modes)
" aM    Select a function or method. Ex: vaM, daM, yaM, caM (normal, operator modes)
" iM    Select inner function or method. Ex: viM, diM, yiM, ciM (normal, operator modes)
" ====  ============================
let g:pymode_motion = 1

let g:pymode_quickfix_minheight = 6
let g:pymode_quickfix_maxheight = 12
let g:pymode_preview_height = &previewheight
let g:pymode_preview_position = 'botright'

" code folding
let g:pymode_folding=1

" pep8 indents
let g:pymode_indent=1
"
" documentation
let g:pymode_doc=1
let g:pymode_doc_bind='K'

" virtualenv
let g:pymode_virtualenv=1

" code running
let g:pymode_run=1
let g:pymode_run_bind='<leader>r'

" breakpoints
let g:pymode_breakpoint=1
let g:pymode_breakpoint_key='<leader>b'

" lints
" *:PymodeLint* -- Check code in current buffer
" *:PymodeLintToggle* -- Toggle code checking
" *:PymodeLintAuto* -- Fix PEP8 errors in current buffer automatically
let g:pymode_lint=1
let g:pymode_lint_on_write = 1
let g:pymode_lint_message = 1
let g:pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe']
" let g:pymode_lint_ignore = ["E501", "W",]
let g:pymode_lint_ignore = ["E501"]
" opens up a new window to show lints
let g:pymode_lint_cwindow = 1
let g:pymode_lint_signs = 1
let g:pymode_lint_todo_symbol = 'WW'
let g:pymode_lint_comment_symbol = 'CC'
let g:pymode_lint_visual_symbol = 'RR'
let g:pymode_lint_error_symbol = 'EE'
let g:pymode_lint_info_symbol = 'II'
let g:pymode_lint_pyflakes_symbol = 'FF'

" syntax highlight
let g:pymode_syntax=1
let g:pymode_syntax_slow_sync=0
let g:pymode_syntax_all=1

" rope
" |:PymodeRopeAutoImport| -- Resolve import for element under cursor
" |:PymodeRopeModuleToPackage| -- Convert current module to package
" |:PymodeRopeNewProject| -- Open new Rope project in current working directory
" |:PymodeRopeRedo| -- Redo changes from last refactoring
" |:PymodeRopeRegenerate| -- Regenerate the project cache
" |:PymodeRopeRenameModule| -- Rename current module
" |:PymodeRopeUndo| -- Undo changes from last refactoring
let g:pymode_rope_lookup_project = 0
let g:pymode_rope=0
let g:pymode_rope_completion=0
let g:pymode_rope_complete_on_dot=0
let g:pymode_rope_auto_project=0
let g:pymode_rope_enable_autoimport=0
let g:pymode_rope_autoimport_generate=0
let g:pymode_rope_guess_project=0
" Keymap for rename method/function/class/variables under cursor
let g:pymode_rope_rename_bind = '<C-c>rr'
" REname current module
let g:pymode_rope_rename_module_bind = '<C-c>r1r'
" organizes imports. unused ones are being dropped.
let g:pymode_rope_organize_imports_bind = '<C-c>ro'
let g:pymode_rope_autoimport_bind = '<C-c>ra'
" convert module to package
let g:pymode_rope_module_to_package_bind = '<C-c>r1p'
"extracting from selected lines
let g:pymode_rope_extract_method_bind = '<C-c>rm'
let g:pymode_rope_extract_variable_bind = '<C-c>rl'
" It happens when you perform move refactoring on a method of a class. In this
" refactoring, a method of a class is moved to the class of one of its
" attributes. The old method will call the new method. If you want to change all
" of the occurrences of the old method to use the new method you can inline it
" afterwards.
let g:pymode_rope_move_bind = '<C-c>rv'

" Change function signature ~
let g:pymode_rope_change_signature_bind = '<C-c>rs'

" }}}

" Some autocommands...----------- {{{

" highlight 'long' lines (>= 80 symbols) in python files
augroup vimrc_autocmds
    autocmd!
    autocmd FileType python,rst,c,cpp highlight Excess ctermbg=DarkGrey guibg=Black
    " write txt files no matter they contain content
    autocmd BufNewFile *.txt :write
    " start new files in insert mode
    " interferes with tagbar...
    " autocmd BufNewFile * :startinsert
    " Disable wrapping for html
    autocmd BufNewFile,BufRead *.html setlocal nowrap
    "(re)indent html files on saving
    autocmd BufWritePre,BufRead *.html :normal gg=G
    autocmd FileType python,rst,c,cpp set nowrap
    " set comulmnmarker to 88 as recommended by black...
    autocmd FileType python,rst,c,cpp set colorcolumn=88
    " python define function or class snippets
    autocmd FileType cpp        :iabbrev <buffer> irv ito::RetVal
    autocmd FileType cpp        :iabbrev <buffer> rv retVal
    autocmd FileType cpp,python :iabbrev <buffer> rr return
    autocmd StdinReadPre * let g:isReadingFromStdin = 1

    " Start with startify as startscreen and NERDTree
    " when not directly opening some file
    autocmd VimEnter * nested if !argc() && !exists('g:isReadingFromStdin') | Startify | endif
    autocmd VimEnter * nested if !argc() && !exists('g:isReadingFromStdin') | NERDTree | endif

    autocmd BufWritePre * %s/\s\+$//e
augroup END
" }}}

" -Markdown plugin----------- {{{
" let g:mkdp_path_to_chrome = "firefox"
" let g:mkdp_browserfunc = 'firefox'
" Callback Vim function to open browser, the only parameter is the url to open.
" set to 1, nvim will open the preview window after entering the markdown buffer
" default: 0
let g:mkdp_auto_start = 0

" set to 1, the nvim will auto close current preview window when change
" from markdown buffer to another buffer
" default: 1
let g:mkdp_auto_close = 0

" set to 1, the vim will refresh markdown when save the buffer or
" leave from insert mode, default 0 is auto refresh markdown as you edit or
" move the cursor
" default: 0
let g:mkdp_refresh_slow = 0

" set to 1, the MarkdownPreview command can be use for all files,
" by default it can be use in markdown file
" default: 0
let g:mkdp_command_for_global = 0

" set to 1, preview server available to others in your network
" by default, the server listens on localhost (127.0.0.1)
" default: 0
let g:mkdp_open_to_the_world = 0

" use custom IP to open preview page
" useful when you work in remote vim and preview on local browser
" more detail see: https://github.com/iamcco/markdown-preview.nvim/pull/9
" default empty
let g:mkdp_open_ip = ''

" specify browser to open preview page
" default: ''
let g:mkdp_browser = ''

" set to 1, echo preview page url in command line when open preview page
" default is 0
let g:mkdp_echo_preview_url = 0

" a custom vim function name to open preview page
" this function will receive url as param
" default is empty
let g:mkdp_browserfunc = ''

" options for markdown render
" mkit: markdown-it options for render
" katex: katex options for math
" uml: markdown-it-plantuml options
" maid: mermaid options
" disable_sync_scroll: if disable sync scroll, default 0
" sync_scroll_type: 'middle', 'top' or 'relative', default value is 'middle'
"   middle: mean the cursor position alway show at the middle of the preview page
"   top: mean the vim top viewport alway show at the top of the preview page
"   relative: mean the cursor position alway show at the relative positon of the preview page
" hide_yaml_meta: if hide yaml metadata, default is 1
" sequence_diagrams: js-sequence-diagrams options
" content_editable: if enable content editable for preview page, default: v:false
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ 'katex': {},
    \ 'uml': {},
    \ 'maid': {},
    \ 'disable_sync_scroll': 0,
    \ 'sync_scroll_type': 'middle',
    \ 'hide_yaml_meta': 1,
    \ 'sequence_diagrams': {},
    \ 'flowchart_diagrams': {},
    \ 'content_editable': v:false
    \ }

" use a custom markdown style must be absolute path
" like '/Users/username/markdown.css' or expand('~/markdown.css')
let g:mkdp_markdown_css = ''

" use a custom highlight style must absolute path
" like '/Users/username/highlight.css' or expand('~/highlight.css')
let g:mkdp_highlight_css = ''

" use a custom port to start server or random for empty
let g:mkdp_port = ''

" preview page title
" ${name} will be replace with the file name
let g:mkdp_page_title = '「${name}」'

augroup vim_markdown
    autocmd!
    autocmd BufNewFile,BufRead *.markdown,*.mdown,*.mkd,*.mkdn,*.mdwn,*.md set ft=markdown
    autocmd FileType md,markdown    nmap <F5> <Plug>MarkdownPreviewToggle
    " autocmd FileType md,markdown    nnoremap <F5> :MarkdownPreview<CR>
augroup END


" }}}

" YouCompleteMe Settings----------- {{{
nnoremap <leader>g :YcmCompleter GoTo<CR>
nnoremap <leader>G :YcmCompleter GoToDefinition<CR>
nnoremap <leader>d :YcmCompleter GoToDeclaration<CR>
nnoremap <leader>D :YcmCompleter GoToImplementation<CR>
nnoremap <leader>j :YcmCompleter GoToReferences<CR>
nnoremap <leader>f :YcmCompleter FixIt<CR>
nnoremap <leader>F :YcmDiag<CR>
" nnoremap <leader>F :YcmCompleter Format<CR>
" nnoremap <leader>E :YcmCompleter ExecuteCommand<CR>
nnoremap <leader>K :YcmCompleter GetDoc<CR>
nnoremap <leader>R :YcmCompleter RefactorRename<CR>
nnoremap <localleader>r :YcmCompleter RestartServer<CR>
"toggle hints, use nmap instead of nnoremap when using plug
nmap <leader>D <plug>(YCMHover)
"always use the recommended parameters for rls completer...
let g:ycm_extra_conf_globlist = ["~/rust_projects/*"]
let g:ycm_enable_diagnostic_signs = 1
let g:ycm_enable_diagnostic_highlighting = 1
let g:ycm_always_populate_location_list = 1
let g:ycm_open_loclist_on_ycm_diags = 1

let g:ycm_key_invoke_completion = '<C-a>'

let g:ycm_complete_in_comments = 1
let g:ycm_seed_identifiers_with_syntax = 1
let g:ycm_collect_identifiers_from_comments_and_strings = 1
" }}}

" Ultisnips settings----------- {{{
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsListSnippets='<c-l>'
let g:UltiSnipsJumpForwardTrigger='<c-k>'
let g:UltiSnipsJumpBackwardTrigger='<c-j>'
let g:UltiSnipsExpandTrigger='<c-k>'
let g:UltiSnipsSnippetDirectories = [$HOME.'/.vim/bundle/vim-snippets/UltiSnips/']
" let g:UltiSnipsSnippetDirectories=['UltiSnips']
" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit='vertical'
"" }}}

" -vimtex settings----------- {{{

let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
let g:tex_flavor="latex"
let g:UltiSnipsRemoveSelectModeMappings = 0
"  " }}}

